# -*- coding: utf-8 -*-
"""Day2_AssignmentQ2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZuR8zhau7P6uJv9ytJzkfq6ig22EnhXT
"""

#Declare two variables and print that which variable is largest using ternary operators

var1 = 10
var2 = 20
largest = var1 if var1 > var2 else var2
print(f"The largest number is: {largest}")

''' #output
The largest number is: 20
'''

