# -*- coding: utf-8 -*-
"""Day2_AssigmentQ1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17BgAbESW5SOfh4Qds38opNUkx47baEQ1
"""

#1. Calculate the multiplication and sum of two numbers
num1 = float(input("Enter first number: "))
num2 = float(input("Enter second number: "))
multiplication = num1*num2
summation = num1+num2
print("Multiplication:", multiplication)
print("Sum:", summation)

''' output
Enter first number: 45
Enter second number: 54
Multiplication: 2430.0
Sum: 99.0
'''

